# Generated by Django 5.0.6 on 2024-07-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default='Por favor actualiza tu perfil'),
            preserve_default=False,
        ),
    ]
